# Operation params
log_level: INFO

jaeger:
  filler: filler

# Input
alerta:
  amqp:
    host: alerta.app.ipl
    port: 5672
    login: TOFILL
    password: TOFILL
  queue: report

db:
 host: pg3.db.ipl
 port: 5432
 database: mon_celery
 user: TOFILL
 password: TOFILL

# Output
reports_dir: reports

# Data sources
ssh:
  user: ddunaev
  id_rsa_filepath: /home/dolan/.ssh/id_rsa
